"use client";

import { useAnalyze } from "@/hooks";
import { IdeaInput } from "@/components/tools/idea-input";
import { BMCResultView } from "@/components/tools/bmc-result";
import { CanvasSkeleton, EmptyState } from "@/components/shared";

export default function CanvasPage() {
  const { result, isLoading, error, analyze } = useAnalyze("canvas");

  const toolIcon = (
    <svg
      className="w-5 h-5"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect x="3" y="3" width="7" height="7" />
      <rect x="14" y="3" width="7" height="7" />
      <rect x="14" y="14" width="7" height="7" />
      <rect x="3" y="14" width="7" height="7" />
    </svg>
  );

  return (
    <div className="max-w-5xl mx-auto">
      <IdeaInput
        tool="canvas"
        onAnalyze={analyze}
        isLoading={isLoading}
        toolName="Business Canvas"
        toolTagline="Generate a full Business Model Canvas in seconds"
        toolIcon={toolIcon}
      />

      {error && (
        <div className="text-sm text-destructive p-4 rounded-xl bg-destructive/10 border border-destructive/20 mb-4">
          Analysis failed. Please check your API key and try again.
        </div>
      )}

      {isLoading && !result && <CanvasSkeleton />}

      {result && <BMCResultView data={result as Partial<import("@/types").CanvasResult>} />}

      {!result && !isLoading && !error && (
        <EmptyState
          icon={toolIcon}
          title="Build your Business Model Canvas"
          description="Describe your idea and get a complete 9-box Business Model Canvas generated by AI."
        />
      )}
    </div>
  );
}
